--Select section: one subquery for each spec using 'ALNVALUE' or 'NUMVALUE' based on spec
SELECT A.ASSETNUM,
       A.DESCRIPTION,
       A.LOCATION,
       A.MANUFACTURER,
       AXLES.NUMVALUE AS AXLES,
       BASE.ALNVALUE AS BASELOCATION,
       CENTER.ALNVALUE AS CENTER,
       CLASS.ALNVALUE AS CLASS,
       COMASSET.ALNVALUE AS COMASSET,
       DRIVER.ALNVALUE AS DRIVER,
       ENGDISP.NUMVALUE AS ENGDISP,
       ENGNUM.ALNVALUE AS ENGNUM,
       FINALPAY.ALNVALUE AS FINALPAY,
       FRNTAXLE.NUMVALUE AS FRNTAXLE,
       FUEL.ALNVALUE AS FUEL,
       GVWR.NUMVALUE AS GVWR,
       MANAGER.ALNVALUE AS MANAGER,
       MANUFACT.ALNVALUE AS MANUFACT,
       MNTHPAY.NUMVALUE AS MNTHPAY,
       MODEL.ALNVALUE AS MODEL,
       NETWT.NUMVALUE AS NETWT,
       OFFROAD.ALNVALUE AS OFFROAD,
       PMREQUIRED.ALNVALUE AS PMREQUIRED,
       PO.ALNVALUE AS PO,
       POLCLASS.ALNVALUE AS POLCLASS,
       QUALOP.ALNVALUE AS QUALOP,
       SERV_TYPE.NUMVALUE AS SERV_TYPE,
       TAREWT.NUMVALUE AS TAREWT,
       USETYPE.ALNVALUE AS USETYPE,
       VCOND.NUMVALUE AS VCOND,
       WHEELS.NUMVALUE AS WHEELS,
       YEARMOD.ALNVALUE AS YEARMOD

--FROM section: from Asset A, then left joining one subquery for each spec       
FROM ASSET A

--subquery for Axles assetpsec (NUMVALE, not ALNVALUE)
LEFT JOIN (SELECT ASP.ASSETNUM,
                  ASP.NUMVALUE
           FROM ASSETSPEC ASP
           WHERE ASP.ASSETATTRID = 'AXLES') AXLES
ON AXLES.ASSETNUM = A.ASSETNUM

--subquery for Baselocation assetpsec (ALNVALUE, not NUMVALUE)
LEFT JOIN (SELECT ASP.ASSETNUM,
                  ASP.ALNVALUE
           FROM ASSETSPEC ASP
           WHERE ASP.ASSETATTRID = 'BASELOCATION') BASE
ON BASE.ASSETNUM = A.ASSETNUM

--subquery for Center assetpsec
LEFT JOIN (SELECT ASP.ASSETNUM,
                  ASP.ALNVALUE
           FROM ASSETSPEC ASP
           WHERE ASP.ASSETATTRID = 'CENTER') CENTER
ON CENTER.ASSETNUM = A.ASSETNUM

--subquery for Class assetpsec
LEFT JOIN (SELECT ASP.ASSETNUM,
                  ASP.ALNVALUE
           FROM ASSETSPEC ASP
           WHERE ASP.ASSETATTRID = 'CLASS') CLASS
ON CLASS.ASSETNUM = A.ASSETNUM

--subquery for COMASSET assetpsec
LEFT JOIN (SELECT ASP.ASSETNUM,
                  ASP.ALNVALUE
           FROM ASSETSPEC ASP
           WHERE ASP.ASSETATTRID = 'COMASSET') COMASSET
ON COMASSET.ASSETNUM = A.ASSETNUM

--subquery for DRIVER assetpsec
LEFT JOIN (SELECT ASP.ASSETNUM,
                  ASP.ALNVALUE
           FROM ASSETSPEC ASP
           WHERE ASP.ASSETATTRID = 'DRIVER') DRIVER
ON DRIVER.ASSETNUM = A.ASSETNUM

--subquery for ENGDISP assetpsec
LEFT JOIN (SELECT ASP.ASSETNUM,
                  ASP.NUMVALUE
           FROM ASSETSPEC ASP
           WHERE ASP.ASSETATTRID = 'ENGDISP') ENGDISP
ON ENGDISP.ASSETNUM = A.ASSETNUM

--subquery for ENGNUM assetpsec
LEFT JOIN (SELECT ASP.ASSETNUM,
                  ASP.ALNVALUE
           FROM ASSETSPEC ASP
           WHERE ASP.ASSETATTRID = 'ENGNUM') ENGNUM
ON ENGNUM.ASSETNUM = A.ASSETNUM

--subquery for FINALPAY assetpsec
LEFT JOIN (SELECT ASP.ASSETNUM,
                  ASP.ALNVALUE
           FROM ASSETSPEC ASP
           WHERE ASP.ASSETATTRID = 'FINALPAY') FINALPAY
ON FINALPAY.ASSETNUM = A.ASSETNUM

--subquery for FRNTAXLE assetpsec
LEFT JOIN (SELECT ASP.ASSETNUM,
                  ASP.NUMVALUE
           FROM ASSETSPEC ASP
           WHERE ASP.ASSETATTRID = 'FRNTAXLE') FRNTAXLE
ON FRNTAXLE.ASSETNUM = A.ASSETNUM

--subquery for FUEL assetpsec
LEFT JOIN (SELECT ASP.ASSETNUM,
                  ASP.ALNVALUE
           FROM ASSETSPEC ASP
           WHERE ASP.ASSETATTRID = 'FUEL') FUEL
ON FUEL.ASSETNUM = A.ASSETNUM

--subquery for GVWR assetpsec
LEFT JOIN (SELECT ASP.ASSETNUM,
                  ASP.NUMVALUE
           FROM ASSETSPEC ASP
           WHERE ASP.ASSETATTRID = 'GVWR') GVWR
ON GVWR.ASSETNUM = A.ASSETNUM

--subquery for MANAGER assetpsec
LEFT JOIN (SELECT ASP.ASSETNUM,
                  ASP.ALNVALUE
           FROM ASSETSPEC ASP
           WHERE ASP.ASSETATTRID = 'MANAGER') MANAGER
ON MANAGER.ASSETNUM = A.ASSETNUM

--subquery for MANUFACT assetpsec
LEFT JOIN (SELECT ASP.ASSETNUM,
                  ASP.ALNVALUE
           FROM ASSETSPEC ASP
           WHERE ASP.ASSETATTRID = 'MANUFACT') MANUFACT
ON MANUFACT.ASSETNUM = A.ASSETNUM

--subquery for MNTHPAY assetpsec
LEFT JOIN (SELECT ASP.ASSETNUM,
                  ASP.NUMVALUE
           FROM ASSETSPEC ASP
           WHERE ASP.ASSETATTRID = 'MNTHPAY') MNTHPAY
ON MNTHPAY.ASSETNUM = A.ASSETNUM

--subquery for MODEL assetpsec
LEFT JOIN (SELECT ASP.ASSETNUM,
                  ASP.ALNVALUE
           FROM ASSETSPEC ASP
           WHERE ASP.ASSETATTRID = 'MODEL') MODEL
ON MODEL.ASSETNUM = A.ASSETNUM

--subquery for NETWT assetpsec
LEFT JOIN (SELECT ASP.ASSETNUM,
                  ASP.NUMVALUE
           FROM ASSETSPEC ASP
           WHERE ASP.ASSETATTRID = 'NETWT') NETWT
ON NETWT.ASSETNUM = A.ASSETNUM

--subquery for OFFROAD assetpsec
LEFT JOIN (SELECT ASP.ASSETNUM,
                  ASP.ALNVALUE
           FROM ASSETSPEC ASP
           WHERE ASP.ASSETATTRID = 'OFFROAD') OFFROAD
ON OFFROAD.ASSETNUM = A.ASSETNUM

--subquery for PMREQUIRED assetpsec
LEFT JOIN (SELECT ASP.ASSETNUM,
                  ASP.ALNVALUE
           FROM ASSETSPEC ASP
           WHERE ASP.ASSETATTRID = 'PMREQUIRED') PMREQUIRED
ON PMREQUIRED.ASSETNUM = A.ASSETNUM

--subquery for PO assetpsec
LEFT JOIN (SELECT ASP.ASSETNUM,
                  ASP.ALNVALUE
           FROM ASSETSPEC ASP
           WHERE ASP.ASSETATTRID = 'PO') PO
ON PO.ASSETNUM = A.ASSETNUM

--subquery for POLCLASS assetpsec
LEFT JOIN (SELECT ASP.ASSETNUM,
                  ASP.ALNVALUE
           FROM ASSETSPEC ASP
           WHERE ASP.ASSETATTRID = 'POLCLASS') POLCLASS
ON POLCLASS.ASSETNUM = A.ASSETNUM

--subquery for QUALOP assetpsec
LEFT JOIN (SELECT ASP.ASSETNUM,
                  ASP.ALNVALUE
           FROM ASSETSPEC ASP
           WHERE ASP.ASSETATTRID = 'QUALOP') QUALOP
ON QUALOP.ASSETNUM = A.ASSETNUM

--subquery for SERV_TYPE assetpsec
LEFT JOIN (SELECT ASP.ASSETNUM,
                  ASP.NUMVALUE
           FROM ASSETSPEC ASP
           WHERE ASP.ASSETATTRID = 'SERV_TYPE') SERV_TYPE
ON SERV_TYPE.ASSETNUM = A.ASSETNUM

--subquery for TAREWT assetpsec
LEFT JOIN (SELECT ASP.ASSETNUM,
                  ASP.NUMVALUE
           FROM ASSETSPEC ASP
           WHERE ASP.ASSETATTRID = 'TAREWT') TAREWT
ON TAREWT.ASSETNUM = A.ASSETNUM

--subquery for USETYPE assetpsec
LEFT JOIN (SELECT ASP.ASSETNUM,
                  ASP.ALNVALUE
           FROM ASSETSPEC ASP
           WHERE ASP.ASSETATTRID = 'USETYPE') USETYPE
ON USETYPE.ASSETNUM = A.ASSETNUM

--subquery for VCOND assetpsec
LEFT JOIN (SELECT ASP.ASSETNUM,
                  ASP.NUMVALUE
           FROM ASSETSPEC ASP
           WHERE ASP.ASSETATTRID = 'VCOND') VCOND
ON VCOND.ASSETNUM = A.ASSETNUM

--subquery for WHEELS assetpsec
LEFT JOIN (SELECT ASP.ASSETNUM,
                  ASP.NUMVALUE
           FROM ASSETSPEC ASP
           WHERE ASP.ASSETATTRID = 'WHEELS') WHEELS
ON WHEELS.ASSETNUM = A.ASSETNUM

--subquery for YEARMOD assetpsec
LEFT JOIN (SELECT ASP.ASSETNUM,
                  ASP.ALNVALUE
           FROM ASSETSPEC ASP
           WHERE ASP.ASSETATTRID = 'YEARMOD') YEARMOD
ON YEARMOD.ASSETNUM = A.ASSETNUM

--Where clause - specifying truck/asset criteria, no need to consider Specs here because we handled with subqueries in FROM section
--WHERE (A.ASSETNUM = '50645' or
--A.ASSETNUM = '50922' or
--A.ASSETNUM = '50996' or
--A.ASSETNUM = '51697' or
--A.ASSETNUM = '51712' or
--A.ASSETNUM = '52023' or
--A.ASSETNUM = '52249' or
--A.ASSETNUM = '52339' or
--A.ASSETNUM = '52432' or
--A.ASSETNUM = '52433' or
--A.ASSETNUM = '52709' or
--A.ASSETNUM = '52798' or
--A.ASSETNUM = '52989' or
--A.ASSETNUM = '53127')

WHERE (A.LOCATION = 'CONSTMATFLT' or
A.LOCATION = 'FPPMATFLT' or
A.LOCATION = 'RAILCARFLT' or
A.LOCATION = 'SIMGIDEONFLT' or
A.LOCATION = 'TCFERGUSONFLT')

