SELECT A.LOCATION, 
       A.ITEMNUM,
       A.BINNUM,
       B.DESCRIPTION,
       D.LONGDESC,
       --A.CATEGORY,
       B.ITEMGROUP,
       --A.INVCLASS,
       A.STATUS,
       C.CURBAL,
       A.ISSUEUNIT
       --A.ABCTYPE,
       --A.CCF,
       --A.MINLEVEL,
       --A.DELIVERYTIME,
       --A.ORDERQTY,
       --A.BUYERID,
       --CASE WHEN EXISTS(SELECT 1 FROM DOCLINKS WHERE OWNERTABLE = 'ITEM' and OWNERID = B.ITEMID) THEN 'Yes' ELSE 'No' END AS ATTACHMENT
FROM INVENTORY A
LEFT JOIN ITEM B
ON (A.ITEMNUM = B.ITEMNUM)
LEFT JOIN INVBALANCES C
ON (A.ITEMNUM = C.ITEMNUM)
LEFT JOIN ITEMDESC_VW_L D
ON (A.ITEMNUM = D.ITEMNUM)
WHERE A.STATUS != 'OBSOLETE'