SELECT A.ITEMNUM,
       A.INVENTORYID,
       A.LOCATION,
       A.STATUS,
       A.CATEGORY,
       B.OWNERID
FROM INVENTORY A
LEFT JOIN DOCLINKS B
ON (A.INVENTORYID = B.OWNERID)
WHERE (A.LOCATION = '18' AND A.STATUS != 'OBSOLETE' AND A.CATEGORY= 'STK')