SELECT --LABOR.LABORCODE,
       --LABOR.PERSONID,
       LABOR.STATUS,
       CRAFT.CRAFT,
       --CRAFT.CRAFTID,
       --LABORCRAFTRATE.LABORCODE,
       --LABORCRAFTRATE.CRAFT,
       --CRAFTSKILL.CRAFT,
       LABORCRAFTRATE.RATE,
       LABORCRAFTRATE.RATE*40*52 AS SALARY,
       CRAFT.DESCRIPTION,
       PERSON.PERSONID,
       PERSON.DEPARTMENT,
       PERSON.FIRSTNAME,
       PERSON.LASTNAME
FROM (((MAXIMO.LABOR LABOR
        INNER JOIN MAXIMO.LABORCRAFTRATE LABORCRAFTRATE
           ON (LABOR.LABORCODE = LABORCRAFTRATE.LABORCODE))
       INNER JOIN MAXIMO.PERSON PERSON ON (LABOR.LABORCODE = PERSON.PERSONID))
      INNER JOIN MAXIMO.CRAFT CRAFT ON (LABORCRAFTRATE.CRAFT = CRAFT.CRAFT))
     INNER JOIN MAXIMO.CRAFTSKILL CRAFTSKILL
        ON (CRAFT.CRAFT = CRAFTSKILL.CRAFT)
--WHERE (LABOR.STATUS = 'ACTIVE')