SELECT A.PONUM,
       C.STATUS,
       B.ITEMNUM,
       B.DESCRIPTION,
       B.QUANTITY,
       B.STATUS,
       B.TRANSDATE,
       B.ACTUALDATE
FROM PO C
LEFT JOIN POLINE A
ON (C.PONUM = A.PONUM)
LEFT JOIN MATRECTRANS B
ON (A.ITEMNUM = B.ITEMNUM)
WHERE (C.STATUS = 'APPR') AND (B.STATUS = 'WASSET')